server:
  port: 8081
  servlet:
    context-path: /projectdemo

swagger2:
  enable: true

spring:
  datasource:
    url: jdbc:mysql://106.52.236.109:3306/work1?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    password:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 64000MB
      max-request-size: 6400MB
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
    mapUnderscoreToCamelCase: true